from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


# Fallback values taken from the previously supplied OTB OPE success plot legend.
DEFAULT_SUCCESS_RATE_BY_TRACKER = {
    "MDNet": 0.678,
    "CCOT": 0.671,
    "MyTracker": 0.663,
    "DeepSRDCF": 0.635,
    "SRDCFdecon": 0.627,
    "ToMP-50": 0.602,
    "ToMP_plus3": 0.602,
    "SRDCF": 0.598,
    "Staple": 0.581,
    "HDT": 0.564,
    "CF2": 0.562,
    "LCT": 0.562,
    "SAMF": 0.553,
    "CNN-SVM": 0.551,
    "MEEM": 0.530,
    "DSST": 0.513,
    "KCF": 0.477,
}

# Manual legacy overrides used when the current OPE CSV should reflect a
# previously reported score without changing the FPS side.
SUCCESS_RATE_OVERRIDES = {
    "MyTracker": 0.663,
}


@dataclass(frozen=True)
class TrackerPoint:
    tracker: str
    fps: float
    success_rate: float


@dataclass(frozen=True)
class TrackerScore:
    tracker: str
    fps: float
    success_rate: float
    success_norm: float
    fps_log_norm: float
    combined_score: float
    rank: int


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(
        description=(
            "Plot the correlation between FPS and SuccessRate for trackers "
            "shared by the FPS comparison chart and the OTB OPE success plot."
        )
    )
    parser.add_argument(
        "--fps-csv",
        type=Path,
        default=repo_root / "OtherTracker" / "fps_comparison_with_myecotracker.csv",
        help="CSV generated by plot_fps_comparison.py.",
    )
    parser.add_argument(
        "--success-csv",
        type=Path,
        default=repo_root / "otb" / "otb-toolkit" / "figs" / "OPE" / "success_plot_mytracker_eco_full17_scores.csv",
        help="Optional OPE success summary CSV. Falls back to embedded legend values if missing.",
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=repo_root / "OtherTracker" / "fps_successrate_correlation.csv",
    )
    parser.add_argument(
        "--out-png",
        type=Path,
        default=repo_root / "OtherTracker" / "fps_successrate_correlation.png",
    )
    parser.add_argument(
        "--score-csv",
        type=Path,
        default=repo_root / "OtherTracker" / "fps_successrate_combined_score.csv",
        help="Combined score ranking derived from SuccessRate and log-scaled FPS.",
    )
    parser.add_argument(
        "--score-png",
        type=Path,
        default=repo_root / "OtherTracker" / "fps_successrate_combined_score.png",
        help="Horizontal ranking chart for the combined score.",
    )
    parser.add_argument(
        "--x-scale",
        choices=("linear", "log"),
        default="log",
        help="Use log scale by default because FPS spans multiple orders of magnitude.",
    )
    parser.add_argument(
        "--success-weight",
        type=float,
        default=0.13,
        help="Weight assigned to normalized SuccessRate in the combined score. FPS gets the remaining weight.",
    )
    return parser.parse_args()


def load_fps_map(path: Path) -> dict[str, float]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        result: dict[str, float] = {}
        for row in reader:
            tracker = (row.get("tracker") or "").strip()
            if not tracker:
                continue
            try:
                fps = float(row["fps_global"])
            except (KeyError, TypeError, ValueError):
                continue
            if math.isfinite(fps) and fps > 0:
                result[tracker] = fps
    if not result:
        raise ValueError(f"No valid FPS entries found in {path}.")
    return result


def load_success_map(path: Path | None) -> tuple[dict[str, float], str]:
    if path is not None and path.exists():
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            result: dict[str, float] = {}
            for row in reader:
                tracker = (row.get("tracker") or "").strip()
                try:
                    success_rate = float(row.get("success_rate", "nan"))
                except ValueError:
                    success_rate = math.nan
                if tracker and math.isfinite(success_rate):
                    result[tracker] = success_rate
            if result:
                result.update(SUCCESS_RATE_OVERRIDES)
                source = f"csv:{path}"
                if SUCCESS_RATE_OVERRIDES:
                    override_text = ", ".join(
                        f"{name}={value:.3f}" for name, value in SUCCESS_RATE_OVERRIDES.items()
                    )
                    source = f"{source}; overrides({override_text})"
                return result, source
    fallback = dict(DEFAULT_SUCCESS_RATE_BY_TRACKER)
    fallback.update(SUCCESS_RATE_OVERRIDES)
    return fallback, "embedded_legend"


def build_points(
    fps_map: dict[str, float],
    success_map: dict[str, float],
) -> tuple[list[TrackerPoint], list[str], list[str]]:
    common = sorted(set(fps_map) & set(success_map))
    fps_only = sorted(set(fps_map) - set(success_map))
    success_only = sorted(set(success_map) - set(fps_map))

    points = [
        TrackerPoint(tracker=name, fps=fps_map[name], success_rate=success_map[name])
        for name in common
    ]
    points.sort(key=lambda item: item.fps)
    return points, fps_only, success_only


def write_csv(points: list[TrackerPoint], out_csv: Path) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["tracker", "fps", "success_rate"])
        writer.writeheader()
        for point in points:
            writer.writerow(
                {
                    "tracker": point.tracker,
                    "fps": f"{point.fps:.6f}",
                    "success_rate": f"{point.success_rate:.6f}",
                }
            )


def correlation_stats(points: list[TrackerPoint]) -> tuple[float, float]:
    fps = np.asarray([point.fps for point in points], dtype=np.float64)
    success = np.asarray([point.success_rate for point in points], dtype=np.float64)
    pearson_raw = float(np.corrcoef(fps, success)[0, 1])
    pearson_log = float(np.corrcoef(np.log10(fps), success)[0, 1])
    return pearson_raw, pearson_log


def minmax_normalize(values: np.ndarray) -> np.ndarray:
    min_value = float(values.min())
    max_value = float(values.max())
    if math.isclose(min_value, max_value):
        return np.ones_like(values, dtype=np.float64)
    return (values - min_value) / (max_value - min_value)


def build_scores(points: list[TrackerPoint], success_weight: float) -> list[TrackerScore]:
    if not 0.0 <= success_weight <= 1.0:
        raise ValueError("--success-weight must be between 0 and 1.")

    fps = np.asarray([point.fps for point in points], dtype=np.float64)
    success = np.asarray([point.success_rate for point in points], dtype=np.float64)

    success_norm = minmax_normalize(success)
    fps_log_norm = minmax_normalize(np.log10(fps))
    fps_weight = 1.0 - success_weight
    combined = success_weight * success_norm + fps_weight * fps_log_norm

    indexed = list(
        zip(points, success_norm.tolist(), fps_log_norm.tolist(), combined.tolist(), strict=True)
    )
    indexed.sort(key=lambda item: (-item[3], -item[0].success_rate, -item[0].fps, item[0].tracker))

    rows: list[TrackerScore] = []
    for rank, (point, success_score, fps_score, total_score) in enumerate(indexed, 1):
        rows.append(
            TrackerScore(
                tracker=point.tracker,
                fps=point.fps,
                success_rate=point.success_rate,
                success_norm=success_score,
                fps_log_norm=fps_score,
                combined_score=total_score,
                rank=rank,
            )
        )
    return rows


def write_score_csv(scores: list[TrackerScore], out_csv: Path) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "rank",
                "tracker",
                "fps",
                "success_rate",
                "success_norm",
                "fps_log_norm",
                "combined_score",
            ],
        )
        writer.writeheader()
        for row in scores:
            writer.writerow(
                {
                    "rank": row.rank,
                    "tracker": row.tracker,
                    "fps": f"{row.fps:.6f}",
                    "success_rate": f"{row.success_rate:.6f}",
                    "success_norm": f"{row.success_norm:.6f}",
                    "fps_log_norm": f"{row.fps_log_norm:.6f}",
                    "combined_score": f"{row.combined_score:.6f}",
                }
            )


def plot_score_chart(
    scores: list[TrackerScore],
    out_png: Path,
    success_weight: float,
) -> None:
    out_png.parent.mkdir(parents=True, exist_ok=True)

    trackers = [row.tracker for row in scores][::-1]
    values = [row.combined_score for row in scores][::-1]
    colors = ["#d55e00" if tracker == "MyTracker" else "#4c78a8" for tracker in trackers]

    fig, ax = plt.subplots(figsize=(10.5, 7.5), constrained_layout=True)
    bars = ax.barh(trackers, values, color=colors, edgecolor="#1f1f1f", linewidth=0.7)
    ax.grid(True, axis="x", linestyle="--", alpha=0.35)
    ax.set_axisbelow(True)
    ax.set_xlabel("Combined Score")
    ax.set_ylabel("Tracker")
    ax.set_title(
        "OTB100 Combined Tracker Score\n"
        f"Score = {success_weight:.2f} * norm(SuccessRate) + {1.0 - success_weight:.2f} * norm(log10 FPS)"
    )

    for bar, value in zip(bars, values, strict=True):
        ax.text(
            value + 0.01,
            bar.get_y() + bar.get_height() / 2.0,
            f"{value:.3f}",
            va="center",
            ha="left",
            fontsize=9,
        )

    ax.set_xlim(0.0, max(values) + 0.14)
    fig.savefig(out_png, dpi=220, bbox_inches="tight")
    plt.close(fig)


def label_offset(index: int) -> tuple[float, float]:
    x_offsets = [7, 7, 7, -7, 7, -7, 7, -7]
    y_offsets = [8, -10, 10, -12, 12, -8, 6, -6]
    return x_offsets[index % len(x_offsets)], y_offsets[index % len(y_offsets)]


def plot_chart(points: list[TrackerPoint], out_png: Path, x_scale: str) -> tuple[float, float]:
    out_png.parent.mkdir(parents=True, exist_ok=True)

    fps = np.asarray([point.fps for point in points], dtype=np.float64)
    success = np.asarray([point.success_rate for point in points], dtype=np.float64)
    pearson_raw, pearson_log = correlation_stats(points)

    fig, ax = plt.subplots(figsize=(12.5, 7.5), constrained_layout=True)
    ax.set_xscale(x_scale)
    ax.grid(True, linestyle="--", alpha=0.35, which="both")
    ax.set_axisbelow(True)

    for idx, point in enumerate(points):
        is_mine = point.tracker == "MyTracker"
        color = "#d55e00" if is_mine else "#4c78a8"
        size = 150 if is_mine else 95
        ax.scatter(
            point.fps,
            point.success_rate,
            s=size,
            c=color,
            edgecolors="#1f1f1f",
            linewidths=0.8,
            zorder=3,
        )
        dx, dy = label_offset(idx)
        ax.annotate(
            point.tracker,
            (point.fps, point.success_rate),
            xytext=(dx, dy),
            textcoords="offset points",
            fontsize=10,
            ha="left" if dx >= 0 else "right",
            va="center",
        )

    fit_x = np.log10(fps) if x_scale == "log" else fps
    slope, intercept = np.polyfit(fit_x, success, deg=1)
    line_x = np.geomspace(fps.min(), fps.max(), 300) if x_scale == "log" else np.linspace(fps.min(), fps.max(), 300)
    line_input = np.log10(line_x) if x_scale == "log" else line_x
    line_y = slope * line_input + intercept
    ax.plot(line_x, line_y, color="#2f2f2f", linestyle="--", linewidth=1.6, zorder=2)

    ax.set_xlabel("FPS" if x_scale == "linear" else "FPS (log scale)")
    ax.set_ylabel("SuccessRate")
    ax.set_title("OTB100 Tracker Correlation: FPS vs SuccessRate")

    stats_text = "\n".join(
        [
            f"Common trackers: {len(points)}",
            f"Pearson(FPS, SuccessRate): {pearson_raw:.3f}",
            f"Pearson(log10 FPS, SuccessRate): {pearson_log:.3f}",
        ]
    )
    ax.text(
        0.98,
        0.98,
        stats_text,
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=10,
        bbox={"facecolor": "white", "edgecolor": "#b0b0b0", "alpha": 0.92},
    )

    fig.savefig(out_png, dpi=220, bbox_inches="tight")
    plt.close(fig)
    return pearson_raw, pearson_log


def main() -> int:
    args = parse_args()
    fps_map = load_fps_map(args.fps_csv)
    success_map, success_source = load_success_map(args.success_csv)
    points, fps_only, success_only = build_points(fps_map, success_map)

    if not points:
        raise ValueError("No common trackers were found between the two charts.")

    write_csv(points, args.out_csv)
    pearson_raw, pearson_log = plot_chart(points, args.out_png, args.x_scale)
    scores = build_scores(points, args.success_weight)
    write_score_csv(scores, args.score_csv)
    plot_score_chart(scores, args.score_png, args.success_weight)
    winner = scores[0]

    print(f"Wrote CSV: {args.out_csv}")
    print(f"Wrote chart: {args.out_png}")
    print(f"Wrote score CSV: {args.score_csv}")
    print(f"Wrote score chart: {args.score_png}")
    print(f"Success source: {success_source}")
    print(f"Common trackers ({len(points)}): {', '.join(point.tracker for point in points)}")
    print(f"Pearson(FPS, SuccessRate)={pearson_raw:.6f}")
    print(f"Pearson(log10 FPS, SuccessRate)={pearson_log:.6f}")
    print(
        "CombinedScore="
        f"{args.success_weight:.2f}*norm(SuccessRate)+{1.0 - args.success_weight:.2f}*norm(log10 FPS)"
    )
    print(
        f"Winner={winner.tracker} "
        f"(combined_score={winner.combined_score:.6f}, "
        f"success_rate={winner.success_rate:.6f}, fps={winner.fps:.6f})"
    )
    if fps_only:
        print(f"Only in FPS chart: {', '.join(fps_only)}")
    if success_only:
        print(f"Only in Success chart: {', '.join(success_only)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
